### ISSUE TITLE
Update README.md tags

### ISSUE THREAD

**Issue by alaframboise** [Esri/arcgis-vectortile-style-editor#2]
Hey @odoe, when you get a chance can you update the tags for this repo so my build can pick it up and index it better?

[](Esri Tags: ArcGIS Web Mapping QuickStart)  // maybe add VectorTile Vector Styles...
[](Esri Language: JavaScript)​

Thanks bud.
AL

**Comment by odoe** [comment]
Updated via 4015156

Let me know if those tags work ok.

Thanks!
