### ISSUE TITLE
Title and owner aren't visible

### ISSUE THREAD

**Issue by williamscraigm** [Esri/arcgis-vectortile-style-editor#3]
When I first view my avaialbe layers it looks like this:
![image](https://cloud.githubusercontent.com/assets/1766401/14514676/be127060-01a7-11e6-9909-a61e8651aba6.png)

When I then go and select all the text it looks like this:
![image](https://cloud.githubusercontent.com/assets/1766401/14514684/d8c914d6-01a7-11e6-9cd4-5bd93f9b09b1.png)

Looks like they're white in the style

**Comment by odoe** [comment]
I think this color update might help
https://github.com/Esri/arcgis-vectortile-style-editor/commit/f1f74a5ffa28a5a6d2d3c70ccbbf6c8124fc61af

**Comment by williamscraigm** [comment]
Looks good
