### ISSUE TITLE
Got error when configuring portal 

### ISSUE THREAD

**Issue by suwenjiang** [Esri/arcgis-vectortile-style-editor#4]
hi, when configure with portal get the following error:

http://screencast.com/t/vSYXbTBim

there is any thing need to be modified??

**Comment by CraigCleveland** [comment]
@myyouthlife I was able to get the app working against my Portal this weekend, but it took some modifications to the main.js file to get it to work.  Attached is a copy of that file.  Update lines 46, 50, 60 and 86 in main.js as appropriate.  Hope this helps!

[main.js.txt](https://github.com/Esri/arcgis-vectortile-style-editor/files/661433/main.js.txt)
