### ISSUE TITLE
"Hosted" layers should not be shown in the list of styleable layers

### ISSUE THREAD

**Issue by williamscraigm** [Esri/arcgis-vectortile-style-editor#6]
"Hosted" layers should not be shown in the list of styleable layers.  Hosted layers are read-only and cannot be changed.  You'll get one of these if you publish your own vector tiles from a vtpk.

**Comment by odoe** [comment]
How do I query that out?

Right now I just search for `type:"Vector Tile Service", owner:"{OWNER_NAME}"`

**Comment by odoe** [comment]
Figured it out!
fixed in https://github.com/Esri/arcgis-vectortile-style-editor/commit/f1f74a5ffa28a5a6d2d3c70ccbbf6c8124fc61af

**Comment by williamscraigm** [comment]
Yup, beat me to it.  All about typekeywords.
