### ISSUE TITLE
Disable 'backspace' = browser back to avoid losing unsaved style edits

### ISSUE THREAD

**Issue by laurenancona** [Esri/arcgis-vectortile-style-editor#7]
While editing a style, if the cursor isn't inside the editor box, the delete/backspace button (in Chrome, at least) takes the user back to the auth screen, losing any unsaved changes to the style.

**Comment by odoe** [comment]
handled by chrome now, if I rewrite this json editor in 4x, will manage this differently.

please use the new editor
https://www.esri.com/arcgis-blog/products/developers/mapping/design-custom-basemaps-with-the-new-arcgis-vector-tile-style-editor/
