### ISSUE TITLE
Style editor does not appear to obey center/zoom values set in style

### ISSUE THREAD

**Issue by laurenancona** [Esri/arcgis-vectortile-style-editor#8]
![screen shot 2016-07-22 at 1 04 23 pm](https://cloud.githubusercontent.com/assets/2152151/17064888/dc16731e-500c-11e6-86a1-437d57164b1b.png)

When `center` and `zoom` are set in the attributes, the editor does not seem obey those values when loading a style to edit.

**Comment by odoe** [comment]
not a property of the style
