### ISSUE TITLE
The "No Styles Available" page link to the blog post doesn't work

### ISSUE THREAD

**Issue by Jfairfield1** [Esri/arcgis-vectortile-style-editor#9]
The link in the middle of the screen "this blog post" isn't clickable.

http://esri.github.io/arcgis-vectortile-style-editor/

![image](https://user-images.githubusercontent.com/13153086/30872838-43ba9662-a2a0-11e7-9e75-d5819e51188b.png)

**Comment by bsvensson** [comment]
It's not clickable for me either, but FYI - the URL it's pointing to is https://blogs.esri.com/esri/arcgis/2015/11/19/how-to-customize-esri-vector-basemaps/
